// constants/bancos.js

const bancos = [
  { codigo: '001', nome: 'Banco do Brasil S.A.' },
  { codigo: '003', nome: 'Banco da Amazônia S.A.' },
  { codigo: '004', nome: 'Banco do Nordeste do Brasil S.A.' },
  { codigo: '007', nome: 'Banco Nacional de Desenvolvimento Econômico e Social (BNDES)' },
  { codigo: '010', nome: 'Credicoamo Crédito Rural Cooperativa' },
  { codigo: '011', nome: 'Credit Suisse Hedging-Griffo Corretora de Valores S.A.' },
  { codigo: '012', nome: 'Banco Inbursa S.A.' },
  { codigo: '014', nome: 'State Street Brasil S.A. – Banco Comercial' },
  { codigo: '015', nome: 'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.' },
  {
    codigo: '016',
    nome: 'Cooperativa de Crédito Mútuo dos Despachantes de Trânsito de Santa Catarina e Rio Grande do Sul',
  },
  { codigo: '017', nome: 'BNY Mellon Banco S.A.' },
  { codigo: '018', nome: 'Banco Tricury S.A.' },
  { codigo: '021', nome: 'Banestes S.A. Banco do Estado do Espírito Santo' },
  { codigo: '024', nome: 'Banco Bandepe S.A.' },
  { codigo: '025', nome: 'Banco Alfa S.A.' },
  { codigo: '029', nome: 'Banco Itaú Consignado S.A.' },
  { codigo: '033', nome: 'Banco Santander (Brasil) S.A.' },
  { codigo: '036', nome: 'Banco Bradesco BBI S.A.' },
  { codigo: '037', nome: 'Banco do Estado do Pará S.A.' },
  { codigo: '040', nome: 'Banco Cargill S.A.' },
  { codigo: '041', nome: 'Banco do Estado do Rio Grande do Sul S.A.' },
  { codigo: '047', nome: 'Banco do Estado de Sergipe S.A.' },
  { codigo: '062', nome: 'Hipercard Banco Múltiplo S.A.' },
  { codigo: '063', nome: 'Banco Bradescard S.A.' },
  { codigo: '064', nome: 'Goldman Sachs do Brasil Banco Múltiplo S.A.' },
  { codigo: '065', nome: 'Banco Andbank (Brasil) S.A.' },
  { codigo: '066', nome: 'Banco Morgan Stanley S.A.' },
  { codigo: '069', nome: 'Banco Crefisa S.A.' },
  { codigo: '070', nome: 'Banco de Brasília S.A. (BRB)' },
  { codigo: '074', nome: 'Banco J. Safra S.A.' },
  { codigo: '075', nome: 'Banco ABN AMRO S.A.' },
  { codigo: '076', nome: 'Banco KDB do Brasil S.A.' },
  { codigo: '077', nome: 'Banco Inter S.A.' },
  { codigo: '078', nome: 'Haitong Banco de Investimento do Brasil S.A.' },
  { codigo: '079', nome: 'Banco Original do Agronegócio S.A.' },
  { codigo: '080', nome: 'B&T Corretora de Câmbio Ltda.' },
  { codigo: '081', nome: 'BancoSeguro S.A.' },
  { codigo: '082', nome: 'Banco Topázio S.A.' },
  { codigo: '083', nome: 'Banco da China Brasil S.A.' },
  { codigo: '084', nome: 'Uniprime Norte do Paraná - Cooperativa de Crédito Ltda.' },
  { codigo: '085', nome: 'Cooperativa Central de Crédito Urbano - Cecred' },
  { codigo: '089', nome: 'Cooperativa de Crédito Rural da Região de Mogiana' },
  {
    codigo: '091',
    nome: 'Central de Cooperativas de Economia e Crédito Mútuo do Estado do Espírito Santo - Sicoob Central ES',
  },
  { codigo: '092', nome: 'Brickell S.A. Crédito, Financiamento e Investimento' },
  {
    codigo: '093',
    nome: 'Pólocred Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte',
  },
  { codigo: '094', nome: 'Banco Finaxis S.A.' },
  { codigo: '095', nome: 'Travelex Banco de Câmbio S.A.' },
  { codigo: '096', nome: 'Banco B3 S.A.' },
  {
    codigo: '097',
    nome: 'Cooperativa Central de Crédito Noroeste Brasileiro Ltda. - Sicoob Central N/NE',
  },
  { codigo: '098', nome: 'Credialiança Cooperativa de Crédito Rural' },
  {
    codigo: '099',
    nome: 'Uniprime Central – Central Interestadual de Cooperativas de Crédito Ltda.',
  },
  { codigo: '100', nome: 'Planner Corretora de Valores S.A.' },
  { codigo: '101', nome: 'Renascença Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  {
    codigo: '102',
    nome: 'XP Investimentos Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
  },
  { codigo: '104', nome: 'Caixa Econômica Federal' },
  { codigo: '0104', nome: 'Caixa Econômica Federal' },
  { codigo: '105', nome: 'Lecca Crédito, Financiamento e Investimento S.A.' },
  { codigo: '107', nome: 'Banco Bocom BBM S.A.' },
  { codigo: '108', nome: 'PortoCred S.A. Crédito, Financiamento e Investimento' },
  { codigo: '111', nome: 'Oliveira Trust Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '113', nome: 'Magliano S.A. Corretora de Cambio e Valores Mobiliarios' },
  {
    codigo: '114',
    nome: 'Central Cooperativa de Crédito no Estado do Espírito Santo - Sicoob Central ES',
  },
  { codigo: '117', nome: 'Advanced Corretora de Câmbio Ltda.' },
  { codigo: '118', nome: 'Standard Chartered Bank (Brasil) S.A. Banco de Investimento' },
  { codigo: '119', nome: 'Banco Western Union do Brasil S.A.' },
  { codigo: '120', nome: 'Banco Rodobens S.A.' },
  { codigo: '121', nome: 'Banco Agibank S.A.' },
  { codigo: '122', nome: 'Banco Bradesco BERJ S.A.' },
  { codigo: '124', nome: 'Banco Woori Bank do Brasil S.A.' },
  { codigo: '125', nome: 'Brasil Plural S.A' },
  { codigo: '126', nome: 'BR Partners Banco de Investimento S.A.' },
  { codigo: '127', nome: 'Codepe Corretora de Valores e Câmbio S.A.' },
  { codigo: '128', nome: 'MS Bank S.A. Banco de Câmbio' },
  { codigo: '129', nome: 'UBS Brasil Banco de Investimento S.A.' },
  { codigo: '130', nome: 'Caruana S.A. Sociedade de Crédito, Financiamento e Investimento' },
  { codigo: '131', nome: 'Tullett Prebon Brasil Corretora de Valores e Câmbio Ltda.' },
  { codigo: '132', nome: 'ICBC do Brasil Banco Múltiplo S.A.' },
  {
    codigo: '133',
    nome: 'Confederação Nacional das Cooperativas Centrais de Crédito e Economia Familiar e Empresarial – CNACRED',
  },
  { codigo: '134', nome: 'BGC Liquidez Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '135', nome: 'Gradual Corretora de Câmbio, Títulos e Valores Mobiliários S.A.' },
  {
    codigo: '136',
    nome: 'Confederação Nacional das Cooperativas Centrais Unicred Ltda. – Unicred do Brasil',
  },
  { codigo: '137', nome: 'Multimoney Corretora de Câmbio Ltda.' },
  { codigo: '138', nome: 'Get Money Corretora de Câmbio S.A.' },
  { codigo: '139', nome: 'Intesa Sanpaolo Brasil S.A. – Banco Múltiplo' },
  { codigo: '140', nome: 'Easynvest - Título Corretora de Valores S.A.' },
  { codigo: '141', nome: 'Travelex Confidence Câmbio S.A.' },
  { codigo: '142', nome: 'Caruana Sociedade de Crédito e Financiamento' },
  { codigo: '143', nome: 'Central dos Cooperados do Sistema Sicoob Confederação' },
  { codigo: '144', nome: 'Banco Modal S.A.' },
  { codigo: '145', nome: 'Paraná Banco S.A.' },
  { codigo: '146', nome: 'Banco Mindset' },
  { codigo: '147', nome: 'Omni S.A. Crédito, Financiamento e Investimento' },
  { codigo: '148', nome: 'Cooperativa de Crédito Rural com Interação Solidária' },
  { codigo: '149', nome: 'Banco SmartBank' },
  { codigo: '150', nome: 'Banco Confidence' },
  { codigo: '151', nome: 'Banco Neon S.A.' },
  { codigo: '152', nome: 'Creditas Sociedade de Crédito Direto S.A.' },
  { codigo: '153', nome: 'Bexs Banco de Câmbio S.A.' },
  { codigo: '154', nome: 'Banco XP S.A.' },
  { codigo: '155', nome: 'Banco Renner S.A.' },
  { codigo: '156', nome: 'Banco Digi S.A.' },
  { codigo: '157', nome: 'Banco Facta S.A.' },
  { codigo: '158', nome: 'Banco Original S.A.' },
  { codigo: '159', nome: 'Banco da Amazonia S.A.' },
  { codigo: '160', nome: 'Banco Pan S.A.' },
  { codigo: '163', nome: 'Commerzbank Brasil S.A Banco Múltiplo' },
  { codigo: '168', nome: 'HSBC Finance (Brasil) S.A. (Banco Múltiplo)' },
  { codigo: '169', nome: 'Banco Olé Bonsucesso Consignado S.A.' },
  { codigo: '172', nome: 'Albatross Ccv S.A.' },
  { codigo: '173', nome: 'BRL Trust Dtvm Sa' },
  { codigo: '174', nome: 'Pernambucanas Financ S.A.' },
  { codigo: '177', nome: 'Guide Investimentos S.A. Corretora de Valores' },
  { codigo: '180', nome: 'Cm Capital Markets Cctvm Ltda' },
  { codigo: '182', nome: 'Dacasa Financeira S/A' },
  { codigo: '183', nome: 'Socred S.A.' },
  { codigo: '184', nome: 'Banco Itaú BBA S.A.' },
  { codigo: '188', nome: 'Ativa S.A Investimentos' },
  { codigo: '189', nome: 'HS Financeira' },
  { codigo: '190', nome: 'Servicoop' },
  { codigo: '191', nome: 'Nova Futura Ctvm Ltda' },
  { codigo: '194', nome: 'Parmetal Dtvm Ltda' },
  { codigo: '196', nome: 'Banco Fair Cc S.A.' },
  { codigo: '197', nome: 'Stone Pagamentos S.A.' },
  { codigo: '204', nome: 'Banco Bradesco Cartões S.A.' },
  { codigo: '208', nome: 'Banco BTG Pactual S.A.' },
  { codigo: '212', nome: 'Banco Matone S.A.' },
  { codigo: '213', nome: 'Banco Arbi S.A.' },
  { codigo: '214', nome: 'Banco Dibens S.A.' },
  { codigo: '215', nome: 'Banco Comercial e de Investimento Sudameris S.A.' },
  { codigo: '217', nome: 'Banco John Deere S.A.' },
  { codigo: '218', nome: 'Banco Bs2 S.A.' },
  { codigo: '222', nome: 'Banco Credit Agricole Brasil S.A.' },
  { codigo: '224', nome: 'Banco Fibra S.A.' },
  { codigo: '225', nome: 'Banco Brascan S.A.' },
  { codigo: '229', nome: 'Banco Cruzeiro do Sul S.A.' },
  { codigo: '230', nome: 'Unicard Banco Múltiplo S.A.' },
  { codigo: '233', nome: 'Banco GE Capital S.A.' },
  { codigo: '237', nome: 'Banco Bradesco S.A.' },
  { codigo: '241', nome: 'Banco Clássico S.A.' },
  { codigo: '243', nome: 'Banco Máxima S.A.' },
  { codigo: '246', nome: 'Banco ABC Brasil S.A.' },
  { codigo: '248', nome: 'Banco Boavista Interatlântico S.A.' },
  { codigo: '249', nome: 'Banco Investcred Unibanco S.A.' },
  { codigo: '250', nome: 'Banco Schahin S.A.' },
  { codigo: '253', nome: 'Bexs Cc S.A.' },
  { codigo: '254', nome: 'Paraná Banco S.A.' },
  { codigo: '259', nome: 'MONEYCORP Banco de Câmbio S.A.' },
  { codigo: '260', nome: 'Nu Pagamentos S.A (Nubank)' },
  { codigo: '263', nome: 'Banco Cacique S.A.' },
  { codigo: '265', nome: 'Banco Fator S.A.' },
  { codigo: '266', nome: 'Banco Cédula S.A.' },
  { codigo: '268', nome: 'Barigui Companhia Hipotecária' },
  { codigo: '269', nome: 'HSBC Banco de Investimento' },
  { codigo: '270', nome: 'Sagitur Cc Ltda' },
  { codigo: '271', nome: 'IB Cctvm Ltda' },
  { codigo: '272', nome: 'AGK Corretora de Câmbio S.A.' },
  { codigo: '273', nome: 'CCR de São Miguel do Oeste' },
  { codigo: '274', nome: 'Money Plus Sociedade de Crédito' },
  { codigo: '276', nome: 'Senff S.A.' },
  { codigo: '278', nome: 'Genial Investimentos Cvm S.A.' },
  { codigo: '279', nome: 'CCR de Primavera do Leste' },
  { codigo: '280', nome: 'Avista S.A.' },
  { codigo: '281', nome: 'Cooperativa de Crédito Rural Coopavel' },
  { codigo: '283', nome: 'RB Capital Investimentos Dtvm Ltda' },
  { codigo: '285', nome: 'Frente Cc Ltda' },
  { codigo: '286', nome: 'Cooperativa de Crédito Rural de Ouro' },
  { codigo: '288', nome: 'Carol Dtvm Ltda' },
  { codigo: '289', nome: 'Decyseo Corretora de Câmbio Ltda' },
  { codigo: '290', nome: 'PagSeguro Internet S.A.' },
  { codigo: '292', nome: 'BS2 Distribuidora de Títulos e Investimentos' },
  { codigo: '293', nome: 'Lastro Rdv Dtvm Ltda' },
  { codigo: '296', nome: 'Vision S.A. Corretora de Câmbio' },
  { codigo: '298', nome: "VIP's Cc Ltda" },
  { codigo: '299', nome: 'Sorocred Crédito, Financiamento e Investimento S.A.' },
  { codigo: '300', nome: 'Banco de La Nación Argentina' },
  { codigo: '301', nome: 'BPP Instituição de Pagamentos S.A.' },
  { codigo: '306', nome: 'Portopar Distribuidora de Títulos e Valores Mobiliários' },
  { codigo: '307', nome: 'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários' },
  { codigo: '309', nome: 'Cambionet Corretora de Câmbio Ltda' },
  { codigo: '310', nome: 'Vortx Dtvm Ltda' },
  { codigo: '313', nome: 'Amazônia Corretora de Câmbio Ltda' },
  { codigo: '315', nome: 'PI Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '318', nome: 'Banco BMG S.A.' },
  { codigo: '319', nome: 'OM Distribuidora de Títulos e Valores Mobiliários Ltda' },
  { codigo: '320', nome: 'Banco Industrial e Comercial S.A.' },
  { codigo: '322', nome: 'Cooperativa de Crédito Rural de Abelardo Luz (Sulcredi/Crediluz)' },
  { codigo: '323', nome: 'Mercado Pago (Conta do Mercado Livre)' },
  { codigo: '324', nome: 'Cartos Sociedade de Crédito Direto S.A.' },
  { codigo: '325', nome: 'Órama Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '326', nome: 'Parati Crédito, Financiamento e Investimento S.A.' },
  { codigo: '329', nome: 'QI Sociedade de Crédito Direto S.A.' },
  { codigo: '330', nome: 'Banco Bari de Investimentos e Financiamentos S.A.' },
  { codigo: '331', nome: 'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '332', nome: 'Acesso Soluções de Pagamento S.A.' },
  { codigo: '335', nome: 'Banco Digio S.A.' },
  { codigo: '336', nome: 'Banco C6 S.A (C6 Bank)' },
  { codigo: '340', nome: 'Super Pagamentos S/A (Superdital)' },
  { codigo: '341', nome: 'Itaú Unibanco S.A.' },
  { codigo: '342', nome: 'Creditas Sociedade de Crédito Direto S.A.' },
  { codigo: '343', nome: 'FFA Sociedade de Crédito ao Microempreendedor' },
  { codigo: '348', nome: 'Banco XP S.A.' },
  { codigo: '349', nome: 'AL5 S.A. Crédito, Financiamento e Investimento' },
  { codigo: '350', nome: 'Cooperativa de Crédito Rural de Pequenos Agricultores' },
  { codigo: '352', nome: 'Toro Corretora de Títulos e Valores Mobiliários Ltda' },
  { codigo: '354', nome: 'Necton Investimentos S.A.' },
  { codigo: '355', nome: 'Ótimo Sociedade de Crédito Direto S.A.' },
  { codigo: '356', nome: 'Banco Real S.A.' },
  { codigo: '359', nome: 'Zema Crédito, Financiamento e Investimento S.A.' },
  { codigo: '360', nome: 'Trinus Capital Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '362', nome: 'Cielo S.A.' },
  { codigo: '363', nome: 'Socopa Sociedade Corretora Paulista S.A.' },
  { codigo: '364', nome: 'Gerencianet S.A.' },
  { codigo: '365', nome: 'Solidus S.A. Corretora de Câmbio e Valores Mobiliários' },
  { codigo: '366', nome: 'Banco Société Générale Brasil S.A.' },
  { codigo: '367', nome: 'Vitreo Distribuidora de Títulos e Valores Mobiliários' },
  { codigo: '368', nome: 'Banco CSF S.A.' },
  { codigo: '370', nome: 'Banco WestLB do Brasil S.A.' },
  { codigo: '371', nome: 'Warren Corretora de Valores Mobiliários e Câmbio Ltda' },
  { codigo: '373', nome: 'UP.P Sociedade de Empréstimo entre Pessoas S.A.' },
  { codigo: '374', nome: 'Realize Crédito, Financiamento e Investimento S.A.' },
  { codigo: '376', nome: 'Banco J.P. Morgan S.A.' },
  {
    codigo: '377',
    nome: 'MS Sociedade de Crédito ao Microempreendedor e Empresa de Pequeno Porte',
  },
  { codigo: '378', nome: 'BBC Leasing S.A. (Arrendamento Mercantil)' },
  { codigo: '379', nome: 'Cooperforte' },
  { codigo: '380', nome: 'PicPay Serviços S.A.' },
  { codigo: '381', nome: 'Banco Mercedes-Benz do Brasil S.A.' },
  { codigo: '382', nome: 'Fidúcia Sociedade de Crédito ao Microempreendedor' },
  { codigo: '383', nome: 'Boletobancario.com Tecnologia de Pagamentos Ltda' },
  { codigo: '384', nome: 'Global Finanças' },
  { codigo: '387', nome: 'Banco Toyota do Brasil S.A.' },
  { codigo: '389', nome: 'Banco Mercantil do Brasil S.A.' },
  { codigo: '390', nome: 'Banco GM S.A.' },
  { codigo: '391', nome: 'Cooperativa de Crédito Rural de Ibiam (Sulcredi/Ibiam)' },
  { codigo: '393', nome: 'Banco Volkswagen S.A.' },
  { codigo: '394', nome: 'Banco Bradesco Financiamentos S.A.' },
  { codigo: '396', nome: 'HUB Pagamentos S.A.' },
  { codigo: '397', nome: 'Listo Sociedade de Crédito Direto S.A.' },
  { codigo: '399', nome: 'HSBC Bank Brasil S.A. (Banco Múltiplo)' },
  { codigo: '403', nome: 'Cora Sociedade de Crédito Direto S.A.' },
  { codigo: '404', nome: 'SumUp Sociedade de Crédito Direto S.A.' },
  { codigo: '408', nome: 'Bônuscred Sociedade de Crédito Direto S.A.' },
  { codigo: '409', nome: 'Unibanco (União de Bancos Brasileiros S.A.)' },
  { codigo: '412', nome: 'Banco Capital S.A.' },
  { codigo: '422', nome: 'Banco Safra S.A.' },
  { codigo: '453', nome: 'Banco Rural S.A.' },
  { codigo: '456', nome: 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.' },
  { codigo: '464', nome: 'Banco Sumitomo Mitsui Brasileiro S.A.' },
  { codigo: '473', nome: 'Banco Caixa Geral (Brasil S.A.)' },
  { codigo: '477', nome: 'Citibank N.A.' },
  { codigo: '479', nome: 'Banco ItaúBank S.A.' },
  { codigo: '487', nome: 'Deutsche Bank S.A. (Banco Alemão)' },
  { codigo: '488', nome: 'JPMorgan Chase Bank' },
  { codigo: '492', nome: 'ING Bank N.V.' },
  { codigo: '494', nome: 'Banco de La República Oriental del Uruguay' },
  { codigo: '495', nome: 'Banco de La Provincia de Buenos Aires' },
  { codigo: '505', nome: 'Banco Credit Suisse (Brasil) S.A.' },
  { codigo: '545', nome: 'Senso Ccvm S.A.' },
  { codigo: '600', nome: 'Banco Luso Brasileiro S.A.' },
  { codigo: '604', nome: 'Banco Industrial do Brasil S.A.' },
  { codigo: '610', nome: 'Banco VR S.A.' },
  { codigo: '611', nome: 'Banco Paulista S.A.' },
  { codigo: '612', nome: 'Banco Guanabara S.A.' },
  { codigo: '613', nome: 'Banco Pecúnia S.A.' },
  { codigo: '623', nome: 'Banco Panamericano S.A.' },
  { codigo: '626', nome: 'Banco Ficsa S.A.' },
  { codigo: '630', nome: 'Banco Intercap S.A.' },
  { codigo: '633', nome: 'Banco Rendimento S.A.' },
  { codigo: '634', nome: 'Banco Triângulo S.A.' },
  { codigo: '637', nome: 'Banco Sofisa S.A.' },
  { codigo: '638', nome: 'Banco Prosper S.A.' },
  { codigo: '641', nome: 'Banco Alvorada S.A.' },
  { codigo: '643', nome: 'Banco Pine S.A.' },
  { codigo: '652', nome: 'Itaú Unibanco Holding S.A.' },
  { codigo: '653', nome: 'Banco Indusval S.A.' },
  { codigo: '654', nome: 'Banco A.J. Renner S.A.' },
  { codigo: '655', nome: 'Banco Votorantim S.A.' },
  { codigo: '707', nome: 'Banco Daycoval S.A.' },
  { codigo: '712', nome: 'Banco Ourinvest S.A.' },
  { codigo: '719', nome: 'Banif-Banco Internacional do Funchal (Brasil) S.A.' },
  { codigo: '721', nome: 'Banco Credibel S.A.' },
  { codigo: '724', nome: 'Banco Porto Seguro S.A.' },
  { codigo: '734', nome: 'Banco Gerdau S.A.' },
  { codigo: '735', nome: 'Banco Pottencial S.A.' },
  { codigo: '738', nome: 'Banco Morada S.A.' },
  { codigo: '739', nome: 'Banco BGN S.A.' },
  { codigo: '740', nome: 'Banco Barclays S.A.' },
  { codigo: '741', nome: 'Banco Ribeirão Preto S.A.' },
  { codigo: '743', nome: 'Banco Semear S.A.' },
  { codigo: '744', nome: 'BankBoston N.A.' },
  { codigo: '745', nome: 'Banco Citibank S.A.' },
  { codigo: '746', nome: 'Banco Modal S.A.' },
  { codigo: '747', nome: 'Banco Rabobank International Brasil S.A.' },
  { codigo: '748', nome: 'Banco Cooperativo Sicredi S.A.' },
  { codigo: '749', nome: 'Banco Simples S.A.' },
  { codigo: '751', nome: 'Dresdner Bank Brasil S.A. (Banco Múltiplo)' },
  { codigo: '752', nome: 'Banco BNP Paribas Brasil S.A.' },
  { codigo: '753', nome: 'NBC Bank Brasil S.A. (Banco Múltiplo)' },
  { codigo: '754', nome: 'Banco Sistema S.A.' },
  { codigo: '755', nome: 'Bank of America Merrill Lynch Banco Múltiplo S.A.' },
  { codigo: '756', nome: 'Banco Cooperativo do Brasil S.A. – BANCOOB' },
  { codigo: '757', nome: 'Banco KEB do Brasil S.A.' },
  { codigo: 'M03', nome: 'Banco Fiat S.A.' },
  { codigo: 'M06', nome: 'Banco de Lage Landen Brasil S.A.' },
  { codigo: 'M07', nome: 'Banco GMAC S.A.' },
  { codigo: 'M08', nome: 'Banco Citicard S.A.' },
  { codigo: 'M09', nome: 'Banco Itaucred Financiamentos S.A.' },
  { codigo: 'M10', nome: 'Banco Moneo S.A.' },
  { codigo: 'M11', nome: 'Banco IBM S.A.' },
  { codigo: 'M12', nome: 'Banco Maxinvest S.A.' },
  { codigo: 'M13', nome: 'Banco Tricury S.A.' },
  { codigo: 'M14', nome: 'Banco Volkswagen S.A.' },
  { codigo: 'M15', nome: 'Banco BRJ S.A.' },
  { codigo: 'M16', nome: 'Banco Rodobens S.A.' },
  { codigo: 'M17', nome: 'Banco Ourinvest S.A.' },
  { codigo: 'M18', nome: 'Banco Ford S.A.' },
  { codigo: 'M19', nome: 'Banco CNH Capital S.A.' },
  { codigo: 'M20', nome: 'Banco Toyota do Brasil S.A.' },
  { codigo: 'M21', nome: 'Banco DaimlerChrysler S.A.' },
  { codigo: 'M22', nome: 'Banco Honda S.A.' },
  { codigo: 'M23', nome: 'Banco Volvo (Brasil) S.A.' },
  { codigo: 'M24', nome: 'Banco PSA Finance Brasil S.A.' },
];

export default bancos;
